### ISSUE TITLE
Mounted Playlist folder option not working

### ISSUE THREAD

**Issue by antipiot** [linuxserver/docker-airsonic#12]
When using Playlist option they're not saved inside mounter directory

<img width="472" alt="airsonic" src="https://user-images.githubusercontent.com/26579988/41202551-a1e0cc80-6cca-11e8-88ba-f2b805f6b04a.PNG">

What is expected:
When creating docker using option playlists, the playlists should be wrote and read from the mounted folder.

What's happening:
When mounting the Playlists folder: nothing is wrote or read from this folder.
If i create a new playlist: nothing appear in the mounted folder but the playlist can be edited.

Where is the playlist stored? coul'dnt find them in docker config.

If i bash into docker and navigate to the playlist location, i'm able to see my playlists.
/airsonic/playlists

<img width="377" alt="airsonic2" src="https://user-images.githubusercontent.com/26579988/41202588-64094f58-6ccb-11e8-9fd3-de465ca40b00.PNG">

Tried to edit airsonic.conf playlist line with no luck:
"PlaylistFolder=/airsonic/playlists"

Any hints?

Regards,

Jonas

**Comment by j0nnymoe** [comment]
You are adding extra information to the container paths when there is no need. The container path doesn't need to be changed from: `-v </path/to/config>:/config \
-v </path/to/music>:/music \
-v </path/to/playlists>:/playlists \
-v </path/to/podcasts>:/podcasts \
-v </path/to/other media>:/media \`

**Comment by antipiot** [comment]
I was mistaken with this,
Issue persist using right path:

<img width="464" alt="airsonic" src="https://user-images.githubusercontent.com/26579988/41202672-fbaaa216-6ccc-11e8-9763-c798ec72076d.PNG">

**Comment by j0nnymoe** [comment]
Just looked at this, the `/playlists` folder is only for importing into airsonic. The playlists are actually stored in the airsonic db.

**Comment by antipiot** [comment]
Okay! was the information i needed. thanks a lot :-)
