### ISSUE TITLE
Limt memory usage of container

### ISSUE THREAD

**Issue by patsaindon** [linuxserver/docker-airsonic#2]
I switched to airsonic after many years using Madsonic, a subsonic fork, wich revoved most of beta testers licences.

In his alpine docker file, he limits the memory usage of the container with ENV JVM_MEMORY=256.

I've been having issues with my host, used has a NAS for HTPC media files (server not accessible). When I stop the container, it fixes the issue.

**Comment by sparklyballs** [comment]
`In his alpine docker file, he` 

who ?

**Comment by patsaindon** [comment]
Here is his docker file:
https://github.com/MadMarty/alpine-madsonic/blob/master/Dockerfile

2017-09-20 7:31 GMT-04:00 sparklyballs <notifications@github.com>:

**Comment by patsaindon** [comment]
Fixed my issues adding this to my docker-compose.yml file:

     environment:
       - JAVA_OPTS=-Xmx256m -Xms256m

Now it will not consume all of the host memory and freeze the movies my
kids are watching.

2017-09-20 7:35 GMT-04:00 Patrick Saindon <pat.saindon@gmail.com>:

**Comment by patsaindon** [comment]
Airsonic works very well in replacement of Madsonic by the way.

**Comment by j0nnymoe** [comment]
@patsaindon good to hear. We just haven't got around to releasing this container yet. I'll make note to add the JAVA_OPTS variable to the readme.
