### ISSUE TITLE
Alpine support

### ISSUE THREAD

**Issue by bobberb** [linuxserver/docker-airsonic#22]
1.3GB of memory is a lot to dedicate to an idle music streaming server. Any chance a rebase to alpine is in the future here?

**Comment by thelamer** [comment]
It is Java, it has nothing to do with the underlying Operating system. 

We specifically have java options for this reason: 
```
-e JAVA_OPTS="-Xmx128M"
```

Try stuff like that to modify the heap size and ensure garbage collection runs sooner. And google up stuff for Java memory usage.

**Comment by BobWs** [comment]
Good to know;)
