### ISSUE TITLE
 10.3.1-RELEASE not loading web page

### ISSUE THREAD

**Issue by screwfaze** [linuxserver/docker-airsonic#23]
Ubuntu

After latest update the login page cannot be displayed with error message below;
Not seeing any errors in the Log from Docker

This page isn’t working
ERR_EMPTY_RESPONSE

Thanks

**Comment by screwfaze** [comment]
![image](https://user-images.githubusercontent.com/17312955/61138312-2c45ee00-a4bf-11e9-9ade-f89ae2227b71.png)

**Comment by aptalca** [comment]
CSRF issue, likely due to reverse proxy

**Comment by screwfaze** [comment]
I'm not actually using reverse proxy for this, I get this even browsing locally by the ip and port number?

**Comment by j0nnymoe** [comment]
Docker run / compose info please

**Comment by screwfaze** [comment]
> Docker run / compose info please

Sorry only know how to do docker run so please explain?

Thanks

**Comment by j0nnymoe** [comment]
Just asking for either your docker run command or docker compose information that you used to create the container.

**Comment by screwfaze** [comment]
OK got you here it is

docker create   --name=airsonic   -e PUID=1000   -e PGID=1000   -e TZ=Europe/London    -p 4040:4040 -v **************:/config   -v **************:/music  --restart unless-stopped   linuxserver/airsonic

**Comment by j0nnymoe** [comment]
Ok, are you hiding personal information with the *'s or something?

**Comment by screwfaze** [comment]
Yes sorry about that

**Comment by j0nnymoe** [comment]
what url are you hitting when you try to browse to airsonic?
Reason I ask, on all our builds, we do a smoke test and on the last one for airsonic, we got the login page ok: https://lsio-ci.ams3.digitaloceanspaces.com/linuxserver/airsonic/latest/index.html

**Comment by screwfaze** [comment]
Just to repeat nothing in my config has changed just the docker image so maybe I will just revert to an older one if you can tell me how to do that.

**Comment by screwfaze** [comment]
How do I pull the image I had before?

Thanks

**Comment by aptalca** [comment]
you use the tags, which you can find here: https://hub.docker.com/r/linuxserver/airsonic/tags

**Comment by j0nnymoe** [comment]
No response for 14 days. Unable to replicate the issue on our own systems with upgrading the container. Please re-open if this is still an issue.
