### ISSUE TITLE
ARM 100% CPU and web interface doesn't respond

### ISSUE THREAD

**Issue by noaho** [linuxserver/docker-airsonic#24]
Hi, I've tried the latest ARM build on Raspberry Pi 3, it comes up and the log looks fine, but the web interface never responds. 

My logs are here: https://pastebin.com/JAj293HG

I think this corresponds to a previous issue here:
https://github.com/linuxserver-archive/docker-airsonic-armhf/issues/2

In that issue, it claims OpenJDK needs to be upgraded to OpenJDK 9, and the issue is closed, but the current version of the JDK is JDK8?

I think this is the base issue upstream, where they also recommend Oracle Java or JDK 9. 
https://github.com/airsonic/airsonic/issues/283

**Comment by thelamer** [comment]
I have just spun this container up on a 64 bit and 32 bit Arm board. (odroid-xu4 and odroid-c2)

Spin it up and go get some coffee, it takes a minute. 

If you want to swap to openjdk-11-jre-headless package locally, test, certify, and vet the change to the container I leave that up to you to PR in.
