### ISSUE TITLE
Starting this container?

### ISSUE THREAD

**Issue by nelsonblaha** [linuxserver/docker-airsonic#3]
I pulled the container and ran it, saw a few hundred lines of SQL-command-type stuff, started the container from `docker ps` ala `docker start id`, and 4040 gets connection refused.

Did I miss a step?

**Comment by tobbenb** [comment]
We haven't released it yet. Seeing that there have been no commits since the first one, it's definitely not ready yet.

**Comment by nelsonblaha** [comment]
Thanks, eagerly awaiting!
