### ISSUE TITLE
Bump JRE to 11

### ISSUE THREAD

**Issue by juerb** [linuxserver/docker-airsonic#33]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Run on JRE 11

## Current Behavior
Runs on JRE 8

## Steps to Reproduce
Upstream moved to JRE 11 could the linuxserver image also be upgraded?
https://github.com/airsonic/airsonic/commit/a453a44a80366737d36e4a13d2f83c4115be0673#diff-87ba2d2b0c6cfbf4eb068c7b4a8e1579

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**

**Comment by aptalca** [comment]
All their docs still recommend openjdk8: https://airsonic.github.io/docs/install/prerequisites/
Also there is a lot of chatter about an upcoming v11 release that mentions bumping jdk version in its roadmap. We should perhaps wait until then (unless we hear from the upstream devs otherwise).
