### ISSUE TITLE
Official Airsonic is deprecated and suggests moving to airsonic-advanced

### ISSUE THREAD

**Issue by lifehackerhansol** [linuxserver/docker-airsonic#34]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Airsonic is no longer maintained.** https://github.com/airsonic/airsonic/commit/5ccca059d5cfe3dd19734c27861b434ea21b43d8
As the Airsonic team has suggested, I think the correct move is to move the Docker to airsonic-advanced.

------------------------------

## Desired Behavior
Airsonic keeps updating, and thus this docker keeps getting updated. 
Since that is not possible, ideally it moves to airsonic-advanced, which is still in active development and thus the Docker gets updated efficiently.

## Current Behavior
Airsonic is deprecated, and thus this Docker won't get any updates.

## Alternatives Considered
A new Docker project for airsonic-advanced may be an option, if it is infeasible to do an in-place migration to airsonic-advanced.

**Comment by CHBMB** [comment]
I was working on an airsonic-advanced image last year.  Ran it locally but couldn't quite get aorund to seeing past the problems with people switching back and forth and database updates.  I've transferred my repository here now, and I'll try and pick it back up, but I am on holiday with the family for the next week, so might be a while.

**Comment by lifehackerhansol** [comment]
> couldn't quite get aorund to seeing past the problems with people switching back and forth and database updates

Well, that won't be a problem now that there is only one option :D

**Comment by CHBMB** [comment]
@lifehackerhansol Yeah, I took a quick look at it last night and did a bit of work before bed.

Essentially their stable v10 branch hasn't seen a release for a long time, but their v11 branch is seeing a lot of dev.

I seem to remember that the reason I didn't release it was I couldn't get the upgrade path from airsonic to airsonic-advanced v10 to airsonic-advanced v11 to work reliably and given it was well over a year ago and the final outcome of forking (yet again) wasn't known, as well as getting busy with IRL stuff meant I just sidelined it.

Now airsonic is being deprecated that removes one barrier, but for support reasons I think an in place upgrade will come with a YMMV caveat and be unsupported by us.

**Comment by lifehackerhansol** [comment]
A seamless upgrade to airsonic-advanced would be the preferred option. I think an alternative is to maybe start a new airsonic-advanced repo without pushing it to the legacy airsonic? That way people who did enjoy airsonic has something, even if it comes with a YMMV caveat but hey you're switching to a different docker completely so that's somewhat expected.

**Comment by CHBMB** [comment]
Yeah, I agree that would be the preferred option, but it's also kind of outside our locus of control.  I was never intending to just pave over this repo with airsonic-advanced, that would be a world of pain from a support point of  view.  I already had a airsonic-advanced repo from 14 months ago on my personal github which I've transferred across and am working on.  Got the v10.6.0 version working (at least on x64) and just tested the v11 branch on x64 and that's running too.

https://github.com/linuxserver/docker-airsonic-advanced

If you want to test the builds are at [chbmb/airsonic-advanced](https://hub.docker.com/r/chbmb/airsonic-advanced/tags?page=1&ordering=last_updated)

I can't test updates from airsonic at the moment as I'm away from home and we're using it wilst we're on holiday so I really don't want to start messing with my install right now.

**Comment by 183amir** [comment]
any progress?

**Comment by lifehackerhansol** [comment]
Decided to give the Docker linked above a try as I haven't really thought much about it since, and it seems to work fine. I haven't really tested migrations, but from what I'm reading here we aren't looking to move this repo from airsonic -> airsonic advanced anyway.

I want to suggest that this repository be archived, if it is indeed the plan to move to a new repository for airsonic advanced. It's fairly clear that airsonic has permanently ceased development so I can't think of why this Docker would have to still be up.
